######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 21 16:44:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
