######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 23:40:53 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/chemikadze/programming/matr/. .

# Input
HEADERS += matrix.h
SOURCES += main.cpp matrix.cpp
