######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 27 20:06:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = bindir
OBJECTS_DIR = objdir

# Input
HEADERS += box.h
SOURCES += box.cpp main.cpp
