######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 18 19:33:27 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
