######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 16:42:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
