######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 28 21:03:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += computerwidget.h computer.h notebook.h window.h
SOURCES += computerwidget.cpp computer.cpp main.cpp notebook.cpp window.cpp
