######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 8 14:33:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
