######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 18 20:57:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gradient.h
SOURCES += main.cpp
