######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 18:16:42 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
