######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 10 00:10:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += intListModel.h
SOURCES += intListModel.cpp main.cpp
