######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 2 23:45:27 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
