######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 3 14:53:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttons.h colorchooser.h mainwindow.h
SOURCES += buttons.cpp colorchooser.cpp main.cpp mainwindow.cpp
RESOURCES += icons.qrc
