# #####################################################################
# Automatically generated by qmake (2.01a) ?? ???. 17 20:28:11 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timer.h
SOURCES += main.cpp \
    timer.cpp
