######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 10 17:24:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += intTableModel.h
SOURCES += intTableModel.cpp main.cpp
