######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 19 20:35:22 2009
######################################################################

TEMPLATE = app
TARGET = simple
DEPENDPATH += . qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += qthread1.h qthread2.h
SOURCES += main.cpp qthread1.cpp qthread2.cpp qtc-gdbmacros/gdbmacros.cpp
