######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 3 21:26:07 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
