######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 26 20:02:18 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
