######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 8 20:19:08 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qstring.cpp
