######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 17:26:14 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
