######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 4 22:03:25 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
