######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 22 23:47:53 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tree.h
SOURCES += main.cpp tree.cpp
