######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 2 21:59:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
