######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 29 13:23:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += progressbar.h tickthread.h
SOURCES += main.cpp progressbar.cpp tickthread.cpp qtc-gdbmacros/gdbmacros.cpp
